#!/usr/bin/env python
import urllib2
from time import ctime
import sys
if not hasattr(sys, "hexversion") or sys.hexversion < 0x20600f0:
  sys.stderr.write("Python 2.6 or greater needed for http://docs.python.org/library/json.html\n")
  sys.exit(1)
import json

url     = 'http://modules.rc.fas.harvard.edu/api/1/avail/'
content = urllib2.urlopen(url)
avail   = json.load(content)

if avail['errors'] != 0:
  raise Exception

for module_name, module_data in sorted(avail['modules'].items()):
  try:
    whatis = module_data['whatis']
  except KeyError:
    whatis = "UNKNOWN"
  updated = ctime(module_data['modulefile_updated'])
  help    = module_data['help']
  print "module:", module_name
  print "whatis:", whatis.encode('utf-8')
  print "modulefile updated:", updated, "\n"

print "API data last updated", ctime(avail['updated'])
