#!/usr/bin/env python
"""Query the fasrc modules API"""
import urllib2
from time import ctime
import sys
if not hasattr(sys, "hexversion") or sys.hexversion < 0x20600f0:
    sys.stderr.write("Python 2.6 or greater needed for ")
    sys.stderr.write("http://docs.python.org/library/json.html\n")
    sys.exit(1)
import json

url = 'http://modules.rc.fas.harvard.edu/api/1/avail/'
content = urllib2.urlopen(url)
avail = json.load(content)

if avail['errors'] != 0:
    raise Exception("Problem with API. Please try again later.")

for module_name, module_data in sorted(avail['modules'].items()):
    try:
        whatis = module_data['whatis']
    except KeyError:
        whatis = "UNKNOWN"
    module_help = module_data['help']
    updated = ctime(module_data['modulefile_updated'])
    print "module:", module_name
    print "whatis:", whatis.encode('utf-8')
    print "modulefile updated:", updated, "\n"

print "API data last updated", ctime(avail['updated'])
